export const movies = [
"Cidade de Deus",
"meninas Malvadas",
"O jogo da imitação",
"Pulp Fiction",
"O Auto da Compadecida",
"Tropa de elite",
"Que horas ela volta",
"2 filhos de francisco",
"Minha mãe é uma peça",
"Forrest Gump",
"Clube da luta",
"Parasita",
"Tempos modernos",
"Oldboy",
"Encatada",
"Oppenheimer",
"A Laranja Mecânica",
"taxi Driver",
"O Lobo de Wall Street",
"The King (é com o boyzinho de Duna)",
"O Show de Truman",
"Monty Python and the Holy Grail",
"Monty Python life of brian",
"V de Vendetta",
"Prenda-me se for capaz",
"todos os filmes de Harry Potter",
"Piratas do Caribe 1,2,3 e 4",
"A rede Social",
"Jogos Vorazes",
"jumanji antigo e o novo",
"Eu sou a lenda",
"300",
"Godzilla (2014)",
"2012",
"Velozes e furiosos 4, 5 e 6",
"Kingsman",
"Lucy",
"Free Guy",
"O Máscara",
"G-Force",
"Karate kid 1, 2 e com Jackie Chan",
"Titanic",
"Alice no pais das maravilhas",
"It",
"O pai",
"Django",
"Em busca da Felicidade",
"Jojo Rabit",
"As vantagens de ser invisível",
"Bohemian Rhapsody",
"Marriage Story",
"a vida de PI",
"Corra",
"A fábrica de chocolate (1971) e (2005)",
"Home alone",
"O conde de monte cristo",
"O menino do pijama listrado",
"A teoria de todas as coisas",
"O Psicopata americano",
"Superbad",
"Scott Pilgrim Vs World",
"The Greatest showman",
"O pior vizinho de todos",
"Bastados inglorios",
"ZombieLand",
"Nos precisamos conversar sobre kevin",
"Juno",
"O corpo fechado",
"fragmentado ",
"Mr Glass",
"El Camino",
"Não olhe para cima",
"O Lugar Silencioso",
"Todo mundo em pânico",
"As braquelas",
"A maldição do Chucky",
"Até que a sorte nos separe",
"Guerra mundial Z",
"The Witch",
"Matilda",
"O Poço",
"jumper",
"Circulp de fogo",
"Anabelle",
"A babá",
"John Carter",
"Enola Holmes",
"Hitch",
"Esposa de mitirinha",
"Zohan"
]